server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name:

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quora
    username: postgres
    # password in the original stub
    # password: password
    # Changed the password from password to superuser
    password: superuser

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
          # database-platform: org.hibernate.dialect.PostgreSQL9Dialect
          # Changed the dialect from 9 to 82
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect